FROM --platform=linux/arm64 eclipse-temurin:17-jre

LABEL maintainer="tech@flow.io"

RUN apt update && apt upgrade -y && \
    sed -i s/#networkaddress.cache.ttl=-1/networkaddress.cache.ttl=10/ $JAVA_HOME/conf/security/java.security

COPY environment-provider.jar .
COPY environment-provider-version.txt .
RUN mv environment-provider.jar /root/
RUN mv environment-provider-version.txt /root/
RUN chown root:root /root/environment-provider*

WORKDIR /root
