FROM eclipse-temurin:17-jdk-jammy AS builder

ARG GIT_USERNAME
ARG GIT_PASSWORD
ARG SBT_VERSION
ENV GIT_USERNAME $GIT_USERNAME
ENV GIT_PASSWORD $GIT_PASSWORD
ENV SBT_VERSION $SBT_VERSION

ENV PROJECTS_TO_BUILD "experience catalog label shopify webhook demandware harmonization tax order-messenger bundle metric shopify-markets calculator data-platform"

WORKDIR /root

RUN apt-get update && \
    apt-get install --no-install-recommends -qy openssh-client curl git ruby bash && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /root/.ssh
RUN chmod 0700 /root/.ssh
RUN ssh-keyscan -H github.com >> ~/.ssh/known_hosts
RUN curl -sL "https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz" | gunzip | tar -x -C /usr/local
RUN ln -s /usr/local/sbt/bin/sbt /usr/local/bin/sbt
RUN chmod 0755 /usr/local/bin/sbt

RUN for repo in $PROJECTS_TO_BUILD; do echo $repo; git clone --depth 1 https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/flowcommerce/$repo.git; cd $repo; sbt update; cd -; done

FROM eclipse-temurin:17-jdk-jammy

LABEL maintainer="tech@flow.io"

ARG SBT_VERSION
ENV SBT_VERSION $SBT_VERSION

WORKDIR /root

RUN echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
RUN apt-get update && \
    apt-get install --no-install-recommends -qy bash curl libaom3 libavif13 libc6 libcurl4 libfontconfig1 libfreetype6 libgif7 libjpeg8 liblcms2-2 libpng16-16 libssl3 libtiff5 libwebp7 libwebpdemux2 libxml2 postgresql-client ttf-mscorefonts-installer wkhtmltopdf zlib1g && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://www.princexml.com/download/prince_15.1-1_ubuntu22.04_amd64.deb
RUN dpkg -i prince_15.1-1_ubuntu22.04_amd64.deb

RUN curl -sL "https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz" | gunzip | tar -x -C /usr/local
RUN ln -s /usr/local/sbt/bin/sbt /usr/local/bin/sbt
RUN chmod 0755 /usr/local/bin/sbt
RUN mkdir -p .sbt ivy2

COPY --from=builder /root/.sbt/ .sbt/.
COPY --from=builder /root/.cache/ .cache/.
