#!/usr/bin/env ruby

tag = ARGV.shift.to_s.strip

if tag == ""
  puts "ERROR: Missing tag"
  exit(1)
end

play_image_tag = "flowdocker/play:%s" % tag

def run(command)
  puts "  %s" % command
  system(command)
end

env_provider = File.expand_path(File.join(File.dirname(__FILE__), '/../../environment-provider'))

if !File.directory?(env_provider)
  puts "ERROR: Could not find environment provider project. Expected at #{env_provider}"
end

puts "Fetching latest version number for #{env_provider}"
env_provider_version = Dir.chdir(env_provider) do
  run("git fetch --tags")
  `sem-info tag latest`.strip
end

puts "env_provider_version: #{env_provider_version}"

# Build in a tmp directory to avoid adding anything unnecessary into
# the context.
tmp_dir = "/tmp/docker.play.#{Process.pid}"
begin
  run("mkdir #{tmp_dir}")
  dockerfile = "#{tmp_dir}/Dockerfile"
  File.open(dockerfile, "w") do |out|
    out << IO.read("Dockerfile.play") % tag
  end

  Dir.chdir(tmp_dir) do
    run("echo '#{env_provider_version}' > environment-provider-version.txt")
    run("curl https://s3.amazonaws.com/io.flow.aws-s3-public/util/environment-provider/environment-provider.jar > ./environment-provider.jar")
    exit(1)
    run("docker build -t %s ." % play_image_tag)
  end

  run("docker push %s" % play_image_tag)
ensure
  run("rm -f #{tmp_dir}")
end

puts ""
puts "Completed build and push of #{play_image_tag}"
