#!/usr/bin/env ruby

# Ex:
#
# ./build-play 0.0.19

play_tag = ARGV.shift.to_s.strip

if play_tag == ""
  puts "ERROR: Missing play tag"
  exit(1)
end

play_image_tag = "flowdocker/play:%s" % play_tag

def run(command)
  puts "  %s" % command
  system(command)
end

env_provider = File.expand_path(File.join(File.dirname(__FILE__), '/../../environment-provider'))

if !File.directory?(env_provider)
  puts "ERROR: Could not find environment provider project. Expected at #{env_provider}"
end

puts "Fetching latest version number for #{env_provider}"
env_provider_version = Dir.chdir(env_provider) do
  run("git fetch --tags")
  `sem-info tag latest`.strip
end

puts "env_provider_version: #{env_provider_version}"

# Build in a tmp directory to avoid adding anything unnecessary into
# the context.
tmp_dir = "/tmp/docker.play.#{Process.pid}"
begin
  run("mkdir #{tmp_dir}")
  run("cp Dockerfile.play #{tmp_dir}/Dockerfile")
  run("cp -R utils #{tmp_dir}/utils")

  Dir.chdir(tmp_dir) do
    run("echo '#{env_provider_version}' > environment-provider-version.txt")
    run("curl https://cdn.flow.io/util/environment-provider/environment-provider.jar > ./environment-provider.jar")
    run("docker build --no-cache -t %s ." % play_image_tag)
  end

  run("docker push %s" % play_image_tag)
ensure
  run("rm -rf #{tmp_dir}")
end

puts ""
puts "Completed build and push of #{play_image_tag}"
