#!/usr/bin/env ruby

tag = ARGV.shift.to_s.strip

if tag == ""
  puts "ERROR: Missing tag"
  exit(1)
end

def run(command)
  puts "  %s" % command
  system(command)
end

# Now update the example in the README
puts ""
puts "Updating README.md to include latest version[%s]" % tag
tmp = "/tmp/docker.readme.#{Process.pid}.tmp"
found = false
changed = false
begin
  File.open(tmp, "w") do |out|
    IO.readlines("../README.md").each do |l|
      if md = l.match(/from flowdocker\/play:(.+)/i)
        found = true
        if changed = (tag != md[1])
          l.sub!(md[1], tag)
        end
      end
      out << l
    end
  end

  if found
    if changed
      run("cp #{tmp} ../README.md")
      run("git commit -m 'Update version of flowdocker/play image to #{tag}' ../README.md")
      run("git push origin master")
    else
      puts "  README was not updated as it already referenced version #{tag}"
    end
  else
    puts "** WARNING: Could not find FROM flowdocker/play in ../README.md - update manually to add the latest version"
  end

ensure
  if File.exists?(tmp)
    File.delete(tmp)
  end
end
