#!/usr/bin/env ruby

ORG = "flowdocker"

tag = ARGV.shift.to_s.strip

if tag == ""
  puts "ERROR: Missing tag"
  exit(1)
end

play_base_image = "%s/%s" % [ORG, "play_base"]
play_base_tag = "%s:%s" % [play_base_image, tag]

def run(command)
  puts "  %s" % command
  system(command)
end

puts ""
puts "Starting build of %s" % play_base_tag

run("docker build -f Dockerfile.base -t %s ." % play_base_tag)
run("docker push %s" % play_base_tag)

puts ""
puts "Completed build of %s" % play_base_tag
