#!/usr/bin/env ruby

# Ex:
#
# ./build-play-crypto 0.0.18 0.0.19

base_tag = ARGV.shift.to_s.strip

if base_tag == ""
  puts "ERROR: Missing base tag"
  exit(1)
end

play_crypto_tag = ARGV.shift.to_s.strip

if play_crypto_tag == ""
  puts "ERROR: Missing play_crypto tag"
  exit(1)
end

play_crypto_image_tag = "flowdocker/play_crypto:%s" % play_crypto_tag

def run(command)
  puts "  %s" % command
  system(command)
end

# Build in a tmp directory to avoid adding anything unnecessary into
# the context.
tmp_dir = "/tmp/docker.play_crypto.#{Process.pid}"
begin
  run("mkdir #{tmp_dir}")
  dockerfile = "#{tmp_dir}/Dockerfile"
  File.open(dockerfile, "w") do |out|
    out << IO.read("Dockerfile.play_crypto").strip % base_tag
  end

  Dir.chdir(tmp_dir) do
    run("docker build -t %s ." % play_crypto_image_tag)
  end

  run("docker push %s" % play_crypto_image_tag)
ensure
  run("rm -rf #{tmp_dir}")
end

puts ""
puts "Completed build and push of #{play_crypto_image_tag}"
