FROM flowdocker/play:%s

MAINTAINER tech@flow.io

# install sbt
RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
RUN apt-get update
RUN apt-get install -y --no-install-recommends sbt=0.13.16

# add .sbt and .ivy2 to root directory
WORKDIR /root
RUN mkdir -p .sbt/
RUN mkdir -p .ivy2/
ADD .sbt/ .sbt/.
ADD .ivy2 .ivy2/.
