FROM openjdk:8-jdk

MAINTAINER tech@flow.io

RUN sed -i s/#networkaddress.cache.ttl=-1/networkaddress.cache.ttl=10/ $JAVA_HOME/jre/lib/security/java.security

WORKDIR /root

COPY environment-provider.jar .
COPY environment-provider-version.txt .
