FROM openjdk:8-jdk-alpine

MAINTAINER tech@flow.io

ENV SBT_VERSION 1.1.6

WORKDIR /root

# Install SBT
RUN curl -sL "https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz" | gunzip | tar -x -C /usr/local && \
    ln -s /usr/local/sbt/bin/sbt /usr/local/bin/sbt && \
    chmod 0755 /usr/local/bin/sbt && \
    mkdir -p .sbt/ && \
    mkdir -p .ivy2/

COPY .sbt/ .sbt/.
COPY .ivy2 .ivy2/.
