FROM openjdk:8-jre-alpine

MAINTAINER tech@flow.io

WORKDIR /root

# install stuff
RUN apk add --no-cache bash && \
    apk add --no-cache curl

COPY environment-provider.jar .
COPY environment-provider-version.txt .
