FROM node:12-alpine

LABEL maintainer="tech@flow.io"

# Default to UTF-8 file.encoding
ENV LANG C.UTF-8

ENV NODE_ENV production

WORKDIR /root

COPY environment-provider.jar .
COPY environment-provider-version.txt .

RUN apk update 
RUN apk upgrade
RUN apk add --no-cache openjdk11-jre
RUN npm install -g forever 
RUN apk add --no-cache --update ca-certificates curl
RUN mkdir -p /opt/node/log

COPY .npmrc /opt/node/.npmrc

WORKDIR /opt/node
