#!/usr/bin/env ruby

require "./helpers.rb"
require "erb"

def usage()
  puts ""
  puts "Usage:"
  puts ""
  puts "./build-node_builder <docker_image_version> <node_major_version>"
  puts ""
  puts "Example:  ./build-node_builder 0.2.0 16"
  puts ""
end

node_tag = ARGV.shift.to_s.strip
node_version = ARGV.shift.to_s.strip
github_token_var_name = "GITHUB_TOKEN"

if node_tag == ""
  puts "ERROR: Missing node tag"
  usage
  exit(1)
end

if node_version == ""
  puts "ERROR: Missing node version"
  usage
  exit(1)
end

if ENV[github_token_var_name] == nil
  # GITHUB_TOKEN is required to pull dependencies for building Flow `dev` tool
  puts "ERROR: Required environment variable '#{github_token_var_name}' is missing"
  exit(1)
end

node_image_tag = "flowdocker/node%s_builder:%s" % [node_version, node_tag]
node_image_latest = "flowdocker/node%s_builder:latest" % node_version

env_provider = get_env_providor_location

puts "Fetching latest version number for #{env_provider}"
env_provider_version = Dir.chdir(env_provider) do
  run("git fetch --tags")
  `sem-info tag latest`.strip
end

puts "env_provider_version: #{env_provider_version}"

# Build in a tmp directory to avoid adding anything unnecessary into
# the context.
tmp_dir = "/tmp/docker.node_builder#{node_version}.#{Process.pid}"
begin
  run("mkdir #{tmp_dir}")
  template = File.read('Dockerfile_template.node_builder.erb')
  File.write("#{tmp_dir}/Dockerfile", ERB.new(template).result(binding))

  Dir.chdir(tmp_dir) do
    run("echo '#{env_provider_version}' > environment-provider-version.txt")
    run("curl https://cdn.flow.io/util/environment-provider/environment-provider_2.12-#{env_provider_version}-one-jar.jar > ./environment-provider.jar")
    run("aws s3 cp s3://io.flow.infra/npm/flowtech.npmrc ./.npmrc")
    run("docker build --platform linux/amd64 --no-cache --build-arg GITHUB_TOKEN=#{ENV[github_token_var_name]} -t %s ." % node_image_tag)
  end

  run("docker tag #{node_image_tag} #{node_image_latest}")
  puts ""
  puts "Completed build of #{node_image_tag} and #{node_image_latest}"

  run("docker push %s" % node_image_tag)
  run("docker push %s" % node_image_latest)
  puts ""
  puts "Completed push of #{node_image_tag} and #{node_image_latest}"

rescue StandardError => e
  puts e.message
ensure
  run("rm -rf #{tmp_dir}")
end
