#!/usr/bin/env ruby

require "./helpers.rb"

def usage()
  puts ""
  puts "Usage:"
  puts ""
  puts "./build-node_selenium_chrome <docker_image_version> <node_version> <selenium_standalone_chrome_version>"
  puts ""
  puts "Example:  ./build-node_selenium_chrome 0.2.0 16 103.0"
  puts ""
end

node_tag = ARGV.shift.to_s.strip
node_version = ARGV.shift.to_s.strip
selenium_standalone_chrome_version = ARGV.shift.to_s.strip

if node_tag == ""
  puts "ERROR: Missing node tag"
  usage
  exit(1)
end

if node_version == ""
  puts "ERROR: Missing node version"
  usage
  exit(1)
end

if selenium_standalone_chrome_version == ""
  puts "ERROR: Missing selenium_standalone_chrome_version argument"
  usage
  exit(1)
end

node_image_tag = "flowdocker/node%s_selenium_chrome:%s" % [node_version, node_tag]
node_image_latest = "flowdocker/node%s_selenium_chrome:latest" % node_version

env_provider = get_env_providor_location

puts "Fetching latest version number for #{env_provider}"
env_provider_version = Dir.chdir(env_provider) do
  run("git fetch --tags")
  `sem-info tag latest`.strip
end

puts "env_provider_version: #{env_provider_version}"

# Build in a tmp directory to avoid adding anything unnecessary into
# the context.
tmp_dir = "/tmp/docker.node_selenium_chrome#{node_version}.#{Process.pid}"
begin
  run("mkdir #{tmp_dir}")
  run("NODE_MAJOR_VERSION=#{node_version} SELENIUM_STANDALONE_CHROME_VERSION=#{selenium_standalone_chrome_version} erb Dockerfile_template.node_selenium_chrome.erb > #{tmp_dir}/Dockerfile")

  Dir.chdir(tmp_dir) do
    run("docker build --platform linux/amd64 --no-cache -t %s ." % node_image_tag)
  end

  run("docker tag #{node_image_tag} #{node_image_latest}")
  puts ""
  puts "Completed build of #{node_image_tag} and #{node_image_latest}"

  run("docker push %s" % node_image_tag)
  run("docker push %s" % node_image_latest)
  puts ""
  puts "Completed push of #{node_image_tag} and #{node_image_latest}"

rescue StandardError => e
  puts e.message
ensure
  # run("rm -rf #{tmp_dir}")
end
