#!/usr/bin/env ruby

require "./helpers.rb"
require "erb"

def usage()
  puts ""
  puts "Usage:"
  puts ""
  puts "./build-node_builder <docker_image_version> <node_major_version>"
  puts ""
  puts "Example:  ./build-node_builder 0.2.0 16"
  puts ""
end

node_tag = ARGV.shift.to_s.strip
node_version = ARGV.shift.to_s.strip
github_token_var_name = "GITHUB_TOKEN"

if node_tag == ""
  puts "ERROR: Missing node tag"
  usage
  exit(1)
end

if node_version == ""
  puts "ERROR: Missing node version"
  usage
  exit(1)
end

if ENV[github_token_var_name] == nil
  # GITHUB_TOKEN is required to pull dependencies for building Flow `dev` tool
  puts "ERROR: Required environment variable '#{github_token_var_name}' is missing"
  exit(1)
end

node_image_tag = "flowdocker/node%s_builder:%s" % [node_version, node_tag]
node_image_latest = "flowdocker/node%s_builder:latest" % node_version

# Build in a tmp directory to avoid adding anything unnecessary into
# the context.
tmp_dir = "/tmp/docker.node_builder#{node_version}.#{Process.pid}"
begin
  run("mkdir #{tmp_dir}")
  template = File.read('Dockerfile_template.node_builder.erb')
  File.write("#{tmp_dir}/Dockerfile", ERB.new(template).result(binding))

  Dir.chdir(tmp_dir) do
    run("aws s3 cp s3://io.flow.infra/npm/flowtech.npmrc ./.npmrc")
    sh """
      /kaniko/executor \
      --dockerfile=`pwd`/Dockerfile \
      --context=`pwd` \
      --snapshot-mode=redo \
      --use-new-run \
      --custom-platform=linux/amd64 \
      --build-arg GITHUB_TOKEN=#{ENV[github_token_var_name]} \
      --destination #{node_image_tag}
    """
  end

  sh """
    /kaniko/executor \
    --dockerfile=`pwd`/Dockerfile \
    --context=`pwd` \
    --snapshot-mode=redo \
    --use-new-run \
    --destination #{node_image_latest}
  """

  puts ""
  puts "Completed build of #{node_image_tag} and #{node_image_latest}"

  sh """
    /kaniko/executor \
    --dockerfile=`pwd`/Dockerfile \
    --context=`pwd` \
    --snapshot-mode=redo \
    --use-new-run \
    --destination #{node_image_tag}
  """
  sh """
    /kaniko/executor \
    --dockerfile=`pwd`/Dockerfile \
    --context=`pwd` \
    --snapshot-mode=redo \
    --use-new-run \
    --destination #{node_image_latest}
  """

  puts ""
  puts "Completed push of #{node_image_tag} and #{node_image_latest}"

ensure
  run("rm -rf #{tmp_dir}")
end
